type User {
  _id: ID!
  emails: JSON
  name: String
  createdAt: String
  roles: [String]
  profile: Profile,
  services: PasswordType
  documents: [Document]
  receivedMessages: [Message]
}

input CreateUserProfileInput {
  name: String
  role: String
}

type PasswordType {
    password: Bcrypt
}

type Bcrypt {
    bcrypt: String
}

type Profile {
  name: String
  role: String
  classNumber: String
  classLetter: String,
  classTeacher: String
}
